caps:
  platformName: "android"
  deviceName: "hogwarts"
  automationName: 'UiAutomator1'
  appPackage: "com.xueqiu.android"
  appActivity: ".view.WelcomeActivityAlias"
  noReset: "true"

server:
  ip: "localhost"
  port: "4723"